### ISSUE TITLE
lime --init keeps telling it is missing lime.config.php

### ISSUE THREAD

**Issue by b00gizm** [webmozart/lime#1]
I cannot initialize lime because it seems to miss the lime.config.php file:

```
Exception: Could not find the configuration file "lime.config.php". Run "lime --help" for usage information. in /path/to/project/test/lib/lime2/lib/LimeConfiguration.php on line 62
```

If I copy and paste the provided config file into my project root it will be initialized correctly but will also show the following notice:

```
Creating lime.config.php... exists already!
```

By the way: I tried lime --help too but it exited with the same error as above.

**Comment by webmozart** [comment]
Should be fixed in 60ece7f4cece8ac0490637850edb44482c15377e

Where did you copy the lime.config.php from? If you copied it from the root directory of Lime2, I recommend to delete it and run the --init task again.

**Comment by b00gizm** [comment]
Thanks Bernhard, I'll try it out.

And yes, I copied it from the Lime2 root folder. May this be the cause of my second issue?

**Comment by webmozart** [comment]
Yes, it probably is.

**Comment by b00gizm** [comment]
I works now but there was a bug in your lime.config.php skeleton, see http://github.com/b00giZm/lime/commit/6b0407400f968a0a07dfa27a9641a8aa03e7cd68

I sent my patch via email ;)

**Comment by webmozart** [comment]
Thanks, I integrated your patch in the master branch.
